apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "obot.fullname" . }}
  labels:
    {{- include "obot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "obot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "obot.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      dnsConfig:
        nameservers:
          - 1.1.1.1
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - hostPath:
          path: /dev/mem
          type: ""
        name: dev-mem
      containers:
        - name: {{ .Release.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /dev/mem
              name: dev-mem
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}-{{ .Values.image.arch | default "amd64"}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: {{ .Values.secret.tokenName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key:  {{ .Values.secret.tokenKey }}
 